### ISSUE TITLE
Enable exporting of public address

### ISSUE THREAD

**Issue by furusiyya** [kung-foo/freki#13]
I need access to [ public address ](https://github.com/kung-foo/freki/blob/master/freki.go#L66) for using in my log messages which is private. You can enable exporting of public address?

**Comment by kung-foo** [comment]
Sounds good. Can you create a PR with a new public method like `processor.GetPublicAddresses() []net.IP`?

**Comment by furusiyya** [comment]
Yes, offcourse. I will.
